version: "3"

services:
    gitlab:
        image: gitlab/gitlab-ce:9.0.0-ce.0
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - /tmp/frabiq/gitlab/config:/etc/gitlab 
            - /tmp/frabiq/gitlab/logs:/var/log/gitlab 
            - /tmp/frabiq/gitlab/data:/var/opt/gitlab 
        networks:
            - frabriqueDev 

    jenkins:
        image: jenkins:2.32.3-alpine
        ports:
            - 8081:8080
        volumes:
            - /tmp/frabiq/jenkins:/var/jenkins_home 
        networks:
            - frabriqueDev

    nexus:
        image: sonatype/nexus3
        volumes:
            - /tmp/frabiq/nexus:/nexus-data
        ports:
            - 8082:8081 
        networks:
            - frabriqueDev

networks:
  frabriqueDev:
    driver: bridge