version: "3"

services:
    gitlab:
        image: gitlab/gitlab-ce:9.0.0-ce.0
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - /tmp/fabriq/gitlab/config:/etc/gitlab 
            - /tmp/fabriq/gitlab/logs:/var/log/gitlab 
            - /tmp/fabriq/gitlab/data:/var/opt/gitlab 
        networks:
            - frabriqueDev 

    jenkins:
        image: jenkins:2.32.3-alpine
        ports:
            - 8081:8080
        volumes:
            - /tmp/fabriq/jenkins:/var/jenkins_home 
        networks:
            - frabriqueDev

    nexus:
        image: sonatype/nexus3
        volumes:
            - /tmp/fabriq/nexus:/nexus-data
        ports:
            - 8082:8081 
        networks:
            - frabriqueDev

    rundeck:
        image: jordan/rundeck
        ports:
            - 8083:4440
            - 8483:4443
        volumes:
            - /tmp/fabriq/rundeck/etc:/etc/rundeck
            - /tmp/fabriq/rundeck/var:/var/rundeck
            - /tmp/fabriq/rundeck/varlog:/var/log/rundeck
            - /tmp/fabriq/rundeck/plugins:/opt/rundeck-plugins
            - /tmp/fabriq/rundeck/log:/var/lib/rundeck/logs
            - /tmp/fabriq/rundeck/data:/var/lib/rundeck/var/storage
        environment:
            - RUNDECK_ADMIN_PASSWORD=admin
        networks:
            - frabriqueDev  

    nginx:
        image: nginx
        ports:
            - 8084:80
        volumes:
            - /tmp/fabriq/nginx/html:/usr/share/nginx/html 
        networks:
            - frabriqueDev
            
    sonarqube:
        image: sonarqube:6.3-alpine
        ports:
            - 8085:9000
        volumes:
            - /tmp/fabriq/sonarqube/conf:/opt/sonarqube/conf
            - /tmp/fabriq/sonarqube/data:/opt/sonarqube/data
            - /tmp/fabriq/sonarqube/extensions:/opt/sonarqube/extensions
            - /tmp/fabriq/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        networks:
            - frabriqueDev  

    wekan:
        image: mquandalle/wekan:latest
        ports:
            - 8086:80
        environment:
            - MONGO_URL=mongodb://wekandb/wekan
            - ROOT_URL=http://localhost:8086
        networks:
            - frabriqueDev  
    
    wekandb:
        image: mongo
        volumes:
            - /tmp/fabriq/wekan/mongo:/data/db
        networks:
            - frabriqueDev  

    mattermost:
        image: mattermost/mattermost-preview:3.7
        ports:
            - 8087:8065
        networks:
            - frabriqueDev  

    svn:
        image: marvambass/subversion
        ports:
            - 8090:80
        volumes:
            - /tmp/fabriq/svn/local:/var/local/svn
            - /tmp/fabriq/svn/backup:/var/svn-backup
            - /tmp/fabriq/svn/dav:/etc/apache2/dav_svn/
        networks:
            - frabriqueDev  
        
    bamboo:
        image: cptactionhank/atlassian-bamboo:5.15.3
        ports:
            - 8091:8085
        volumes:
            - /tmp/fabriq/bamboo/data:/var/atlassian/bamboo
            - /tmp/fabriq/bamboo/logs:/opt/atlassian/bamboo/logs
        networks:
            - frabriqueDev  
 
networks:
  frabriqueDev:
    driver: bridge