version: "3"

services:
    gitlab:
        image: gitlab/gitlab-ce:9.0.0-ce.0
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - /tmp/frabiq/gitlab/config:/etc/gitlab 
            - /tmp/frabiq/gitlab/logs:/var/log/gitlab 
            - /tmp/frabiq/gitlab/data:/var/opt/gitlab 
        networks:
            - frabriqueDev 

    jenkins:
        image: jenkins:2.32.3-alpine
        ports:
            - 8081:8080
        volumes:
            - /tmp/frabiq/jenkins:/var/jenkins_home 
        networks:
            - frabriqueDev

    nexus:
        image: sonatype/nexus3
        volumes:
            - /tmp/frabiq/nexus:/nexus-data
        ports:
            - 8082:8081 
        networks:
            - frabriqueDev

    rundeck:
        image: jordan/rundeck
        ports:
            - 8083:4440
            - 8483:4443
        volumes:
            - /tmp/frabiq/rundeck/etc:/etc/rundeck
            - /tmp/frabiq/rundeck/var:/var/rundeck
            - /tmp/frabiq/rundeck/varlog:/var/log/rundeck
            - /tmp/frabiq/rundeck/plugins:/opt/rundeck-plugins
            - /tmp/frabiq/rundeck/log:/var/lib/rundeck/logs
            - /tmp/frabiq/rundeck/data:/var/lib/rundeck/var/storage
        environment:
            - RUNDECK_ADMIN_PASSWORD=admin
        networks:
            - frabriqueDev  

    nginx:
        image: nginx
        ports:
            - 8084:80
        volumes:
            - /tmp/frabiq/nginx/html:/usr/share/nginx/html 
        networks:
            - frabriqueDev 
networks:
  frabriqueDev:
    driver: bridge