version: "3"

services:

   gitlab:
        image: gitlab/gitlab-ce:9.0.0-ce.0
        hostname: <your_ci_uri>
        ports:
            - 8080:80
            - 8443:443
        environment:
            - VIRTUAL_HOST=gitlab.walterFrabriq
            - VIRTUAL_PORT=80                   
        volumes:
            - /home/walter/fabriq/gitlab/config:/etc/gitlab 
            - /home/walter/fabriq/gitlab/logs:/var/log/gitlab 
            - /home/walter/fabriq/gitlab/data:/var/opt/gitlab

  jenkins:
        image: jenkins:2.46.1
        ports:
            - 8081:8080
        environment:
            - VIRTUAL_HOST=jenkins.walterFrabriq
            - VIRTUAL_PORT=8080              
        volumes:
            - /home/walter/fabriq/jenkins:/var/jenkins_home

    nexus:
        image: sonatype/nexus3:3.2.1
        volumes:
            - "/home/walter/fabriq/nexus:/nexus-data"
        ports:
            - 8082:8081 
        environment:
            - VIRTUAL_HOST=nexus.walterFrabriq
            - VIRTUAL_PORT=8081
            
    rundeck:
        image: jordan/rundeck:2.7.3
        ports:
            - 8083:4440
        volumes:
            - /home/walter/fabriq/rundeck/etc:/etc/rundeck
            - /home/walter/fabriq/rundeck/var:/var/rundeck
            - /home/walter/fabriq/rundeck/varlog:/var/log/rundeck
            - /home/walter/fabriq/rundeck/plugins:/opt/rundeck-plugins
            - /home/walter/fabriq/rundeck/log:/var/lib/rundeck/logs
            - /home/walter/fabriq/rundeck/data:/var/lib/rundeck/var/storage
        environment:
            - RUNDECK_ADMIN_PASSWORD=admin
            - SERVER_URL=http://localhost:8083
            - VIRTUAL_HOST=rundeck.walterFrabriq
            - VIRTUAL_PORT=4440

    nginx:
        image: nginx:1.11
        ports:
            - 8084:80
        environment:
            - VIRTUAL_HOST=nginx.walterFrabriq
            - VIRTUAL_PORT=80            
        volumes:
            - /home/walter/fabriq/nginx/html:/usr/share/nginx/html
    
    sonarqube:
        image: sonarqube:6.3
        ports:
            - 8085:9000
        environment:
            - VIRTUAL_HOST=sonar.walterFrabriq
            - VIRTUAL_PORT=9000  
        volumes:
            - /home/walter/fabriq/sonarqube/conf:/opt/sonarqube/conf
            - /home/walter/fabriq/sonarqube/data:/opt/sonarqube/data
            - /home/walter/fabriq/sonarqube/extensions:/opt/sonarqube/extensions
            - /home/walter/fabriq/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

     wekan:
        image: mquandalle/wekan:latest
        ports:
            - 8086:80
        environment:
            - MONGO_URL=mongodb://wekandb/wekan
            - ROOT_URL=http://wekan.walterFrabriq
            - VIRTUAL_HOST=wekan.walterFrabriq
            - VIRTUAL_PORT=80  

    wekandb:
        image: mongo
        volumes:
            - /home/walter/fabriq/wekan/mongo:/data/db           

    mattermost:
        image: mattermost/mattermost-preview:3.7
        ports:
            - 8077:8065
        environment:
            - VIRTUAL_HOST=mattermost.walterFrabriq
            - VIRTUAL_PORT=8065