version: "3"

services:
    tomcat:
        image: jetty:9.4.3
        ports:
            - 8087:8080
            - 8088:8443
        networks:
            - frabriqueDev
networks:
  frabriqueDev:
    driver: bridge
