version: "3"

services:
    mantisbt:
        image: vimagick/mantisbt:latest
        ports:
            - "8989:80"
        links:
            - mysql
        restart: always
        networks:
            - frabriqueDev
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bugtracker
            - MYSQL_USER=mantisbt
            - MYSQL_PASSWORD=mantisbt
        restart: always
        networks:
            - frabriqueDev

networks:
  frabriqueDev:
    driver: bridge
