version: "3"

services:
    db:
        image: mongo
        volumes:
            - /tmp/fabriq/rocketchat/data/runtime/db:/data/db
            - /tmp/fabriq/rocketchat/data/dump:/dump
        command: mongod --smallfiles
        networks:
            - frabriqueDev  

    rocketchat:
        image: rocketchat/rocket.chat:latest
        environment:
            - MONGO_URL=mongodb://db:27017/rocketchat
            - ROOT_URL=https://chat.inumio.com
            - Accounts_UseDNSDomainCheck=True
        links:
            - db:db
        ports:
            - 3000:3000
        networks:
            - frabriqueDev  

    hubot:
        image: rocketchat/hubot-rocketchat:v0.1.4
        environment:
            - ROCKETCHAT_URL=165.114.165.21:3000
            - ROCKETCHAT_ROOM=GENERAL
            - ROCKETCHAT_USER=Botname
            - ROCKETCHAT_PASSWORD=BotPassw0rd
            - BOT_NAME=Botname
            - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
        links:
            - rocketchat:rocketchat
        ports:
            - 3001:8080
        networks:
            - frabriqueDev  

networks:
  frabriqueDev:
    driver: bridge