version: '3'       
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /mnt/B4CC329DCC325A36/Documents/présentations/fabriqueDev/test/nginx.tmpl:/app/nginx.tmpl
    snowcamp:
        image: snowcamp:latest
        container_name: snowcamp
        ports:
            - "81:80"
        environment:
            - VIRTUAL_HOST=fab.snow.ci
    
    
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
        ports:
            - 8092:8081
        environment:
            - VIRTUAL_HOST=artifactory.snow.ci
            - VIRTUAL_PORT=8081              