version: '3'

services:
    #nginx-proxy:
    #    build: ./nginx-proxy
    #    environment:
    #        - DEFAULT_HOST=fab.snow.ci
    #    ports:
    #        - "80:80"
    #    networks:
    #      fabriq_net:
    #        ipv4_address: 172.8.0.2
    #    volumes:
    #        - /var/run/docker.sock:/tmp/docker.sock:ro

    nexus:
        image: sonatype/nexus3:3.7.1
        user: root
        restart: always
        volumes:
            - "/home/snow/fabriq/nexus:/nexus-data"
        ports:
            - 8082:8081 
        environment:
            - VIRTUAL_HOST=nexus.snow.ci
            - VIRTUAL_PORT=8081
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.10
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=nexus"
           - "traefik.frontend.rule=Host:nexus.snow.ci"
    sonarqube:
        image: sonarqube:6.7.1
        user: root
        restart: always
        ports:
            - 8085:9000
        environment:
            - VIRTUAL_HOST=sonar.snow.ci
            - VIRTUAL_PORT=9000  
        volumes:
            - /home/snow/fabriq/sonarqube/conf:/opt/sonarqube/conf
            - /home/snow/fabriq/sonarqube/data:/opt/sonarqube/data
            - /home/snow/fabriq/sonarqube/extensions:/opt/sonarqube/extensions
            - /home/snow/fabriq/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        networks:
#          fabriq_net:
#            ipv4_address: 172.8.0.8
#        labels:
#           - "traefik.docker.network=fabriq_net"
#           - "traefik.backend=sonarqube"
#           - "traefik.frontend.rule=Host:sonarqube.snow.ci"
#    rundeck:
#        image: jordan/rundeck:2.10.4
#        user: root
#        restart: always
#        ports:
#            - 4440:4440
#        volumes:
#            - /home/snow/fabriq/rundeck/etc:/etc/rundeck
#            - /home/snow/fabriq/rundeck/var:/var/rundeck
#            - /home/snow/fabriq/rundeck/varlog:/var/log/rundeck
#            - /home/snow/fabriq/rundeck/plugins:/opt/rundeck-plugins
#            - /home/snow/fabriq/rundeck/log:/var/lib/rundeck/logs
#            - /home/snow/fabriq/rundeck/data:/var/lib/rundeck/var/storage
#            - /home/snow/fabriq/shared:/tmp/fabriq/shared
#        environment:
#            - RUNDECK_ADMIN_PASSWORD=admin
#            - EXTERNAL_SERVER_URL=http://rundeck.snow.ci
#            - VIRTUAL_HOST=rundeck.snow.ci
#            - VIRTUAL_PORT=4440
#        networks:
#          fabriq_net:
#            ipv4_address: 172.8.0.9
#        labels:
#           - "traefik.docker.network=fabriq_net"
#           - "traefik.backend=rundeck"
#           - "traefik.frontend.rule=Host:rundeck.snow.ci"
#    nginx:
#        image: nginx:1.13.8
#        user: root
#        restart: always
#        ports:
#            - 8084:80
#        environment:
#            - VIRTUAL_HOST=nginx.snow.ci
#            - VIRTUAL_PORT=80            
#        volumes:
#            - /home/snow/fabriq/shared:/usr/share/nginx/html
#    jira:
#        image: cptactionhank/atlassian-jira:7.7.0
#        user: root
#        restart: always
#        volumes:
#           - /home/snow/fabriq/jira/jira:/var/atlassian/jira
#           - /home/snow/fabriq/jira/logs:/opt/atlassian/jira/logs
#        ports:
#           - 8097:8080
#        environment:
#           - VIRTUAL_HOST=jira.snow.ci
#           - VIRTUAL_PORT=8080
#        networks:
#          fabriq_net:
#            ipv4_address: 172.8.0.10
#        labels:
#           - "traefik.docker.network=fabriq_net"
#           - "traefik.backend=jira"
#           - "traefik.frontend.rule=Host:jira.snow.ci"
#    mattermost:
#        image: mattermost/mattermost-preview:4.6
#        user: root
#        restart: always
#        ports:
#            - 8077:8065
#        environment:
#            - VIRTUAL_HOST=mattermost.snow.ci
#            - VIRTUAL_PORT=8065
        #volumes:
            #- /home/snow/fabriq/mattermost/data:/mm/mattermost/mattermost-data
            #- /home/snow/fabriq/mattermost/config:/mm/mattermost/config
#        networks:
#          fabriq_net:
#            ipv4_address: 172.8.0.11
#        labels:
#           - "traefik.docker.network=fabriq_net"
#           - "traefik.backend=mattermost"
#           - "traefik.frontend.rule=Host:mattermost.snow.ci"
    prometheus:
        image: prom/prometheus
        ports:
           - 9090:9090
        volumes:
           - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.12
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=prometheus"
           - "traefik.frontend.rule=Host:prometheus.snow.ci"
    node-exporter:
        image: quay.io/prometheus/node-exporter
        ports: 
           - 9100:9100
        volumes:
           - /proc:/host/proc
           - /sys:/host/sys
           - /:/rootfs" 
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.13

