version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        environment:
            - DEFAULT_HOST=fab.snow.ci
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    fabriquedev:
        build: .
        environment:
            - VIRTUAL_HOST=fab.snow.ci
