version: '3'
services:
    nginx-proxy:
        build: ./nginx-proxy
        environment:
            - DEFAULT_HOST=fab.snow.ci
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    fabriquedev:
        build: .
        environment:
            - VIRTUAL_HOST=fab.snow.ci
        #volumes:
        #    - .:/src
    gitlab:
        image: gitlab/gitlab-ce:10.3.3-ce.0
        user: root
        restart: always
        hostname: gitlab.snow.ci
        ports:
            - 8080:80
            - 8443:443
        environment:
            - VIRTUAL_HOST=gitlab.snow.ci
            - VIRTUAL_PORT=80                   
        volumes:
            - /home/snow/fabriq/gitlab/config:/etc/gitlab 
            - /home/snow/fabriq/gitlab/logs:/var/log/gitlab 
            - /home/snow/fabriq/gitlab/data:/var/opt/gitlab

    bash:
        user: $USER_ID
        command: bash
        build: .
        volumes:
            - .:/src
