version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /mnt/B4CC329DCC325A36/Documents/présentations/fabriqueDev/test/nginx.tmpl:/app/nginx.tmpl
    snowcamp:
        image: snowcamp:latest
        container_name: snowcamp
        ports:
            - "81:80"
        environment:
            - VIRTUAL_HOST=fab.snow.ci
    gitlab:
        image: gitlab/gitlab-ce:10.3.3-ce.0
        hostname: gitlab.snow.ci
        ports:
            - 8080:80
            - 8443:443
        environment:
            - VIRTUAL_HOST=gitlab.snow.ci
            - VIRTUAL_PORT=80                   
        volumes:
            - /home/snow/fabriq/gitlab/config:/etc/gitlab 
            - /home/snow/fabriq/gitlab/logs:/var/log/gitlab 
            - /home/snow/fabriq/gitlab/data:/var/opt/gitlab
    jenkins:
        image: jenkins/jenkins:2.102
        ports:
            - 8081:8080
            - 50000:50000
        environment:
            - VIRTUAL_HOST=jenkins.snow.ci
            - VIRTUAL_PORT=8080              
        volumes:
            - /home/snow/fabriq/jenkins:/var/jenkins_home
