version: '3'

networks:
  fabriq_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.8.0.0/16
        #gateway: 172.8.0.1
services:
    traefik:
        image: traefik
        environment:
            - DEFAULT_HOST=fab.snow.ci
        command: --api --docker --logLevel=DEBUG
        ports:
            - "80:80"
            - "8000:8080"
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.toml/:/etc/traefik/traefik.toml
    fabriquedev:
        build: ./frontend/
        environment:
            - VIRTUAL_HOST=fab.snow.ci
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.3
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=fabriquedev"
           - "traefik.frontend.rule=Host:fab.snow.ci"
    gitlab:
        image: gitlab/gitlab-ce:10.3.3-ce.0
        user: root
        restart: always
        hostname: gitlab.snow.ci
        ports:
            - 8080:80
            - 8443:443
        environment:
            - VIRTUAL_HOST=gitlab.snow.ci
            - VIRTUAL_PORT=80                   
        volumes:
            - /home/snow/fabriq/gitlab/config:/etc/gitlab 
            - /home/snow/fabriq/gitlab/logs:/var/log/gitlab 
            - /home/snow/fabriq/gitlab/data:/var/opt/gitlab
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.4
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=gitlab"
           - "traefik.backend.port=8080"
           - "traefik.frontend.rule=Host:gitlab.snow.ci"
    jenkins:
        image: jenkins/jenkins:2.103
        user: root
        restart: always
        ports:
            - 8081:8080
            - 50000:50000
        environment:
            - VIRTUAL_HOST=jenkins.snow.ci
            - VIRTUAL_PORT=8080              
        volumes:
            - /home/snow/fabriq/jenkins:/var/jenkins_home
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.5
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=jenkins"
           - "traefik.frontend.rule=Host:jenkins.snow.ci"
    prometheus:
        image: prom/prometheus
        ports:
           - 9090:9090
        volumes:
           - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.6
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=prometheus"
           - "traefik.frontend.rule=Host:prometheus.snow.ci"
    node-exporter:
        image: quay.io/prometheus/node-exporter
        ports: 
           - 9100:9100
        volumes:
           - /proc:/host/proc
           - /sys:/host/sys
           - /:/rootfs" 
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.7
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=node_exporter"
           - "traefik.frontend.rule=Host:node_exporter.snow.ci"
    grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
        environment:
          - GF_SERVER_ROOT_URL=http://grafana.snow.ci
          - GF_SECURITY_ADMIN_PASSWORD=secret 
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.8
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=grafana"
           - "traefik.frontend.rule=Host:grafana.snow.ci"

