version: '3'       
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /mnt/B4CC329DCC325A36/Documents/présentations/fabriqueDev/test/nginx.tmpl:/app/nginx.tmpl
    snowcamp:
        image: snowcamp:latest
        container_name: snowcamp
        ports:
            - "81:80"
        environment:
            - VIRTUAL_HOST=fab.snow.ci
    
    
    
    mantisbt:
        image: vimagick/mantisbt:latest
        ports:
            - "8989:80"
        links:
            - mysql
        restart: always
        environment:
            - VIRTUAL_HOST=mantis.snow.ci
            - VIRTUAL_PORT=80  
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bugtracker
            - MYSQL_USER=mantisbt
            - MYSQL_PASSWORD=mantisbt
        restart: always

    jira:
        image: cptactionhank/atlassian-jira:7.7.0
        volumes:
            - /mnt/B4CC329DCC325A36/Documents/présentations/fabriqueDev/test/jira/jira:/var/atlassian/jira
            - /mnt/B4CC329DCC325A36/Documents/présentations/fabriqueDev/test/jira/logs:/opt/atlassian/jira/logs
        ports:
            - 8097:8080
        environment:
            - VIRTUAL_HOST=jira.snow.ci
            - VIRTUAL_PORT=8080
    

    wekan:
        image: mquandalle/wekan:latest
        ports:
            - 8086:80
        environment:
            - MONGO_URL=mongodb://wekandb:27017/wekan
            - ROOT_URL=http://wekan.snow.ci
            - VIRTUAL_HOST=wekan.snow.ci
            - VIRTUAL_PORT=80  


    wekandb:
        image: mongo:3.2.18
        container_name: wekan-db
        command: mongod --smallfiles --oplogSize 128
        expose:
            - 27017

