global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['172.8.0.12:9090', '172.8.0.13:9100', 'localhost:9323']
        labels:
          group: 'prometheus'
